{$resource '.\Data\Misc.RES'}

{$resource '.\Data\Cursors.RES'}
{$resource '.\Data\Particles.RES'}
{$resource '.\Data\Sounds.RES'}

{$resource '.\Data\Custom.RES'}

{$resource '.\Data\Orig.RES'}
{$resource '.\Data\Ohno.RES'}
{$resource '.\Data\H93.RES'}
{$resource '.\Data\H94.RES'}
{$resource '.\Data\X91.RES'}
{$resource '.\Data\X92.RES'}

{$resource '.\Data\Orig_music.RES'}
{$resource '.\Data\Ohno_music.RES'}
{$resource '.\Data\H94_music.RES'}












